# Generated by Django 3.0.8 on 2020-07-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='ifsc',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
